#!/usr/bin/env bash
# Args: $APP $IMAGE_TAG

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG)
verify_app_name "$APP"

dokku_log_verbose_quiet "$APP PROCFILE=$(dokku config:get $APP PROCFILE)"

dokku_log_verbose_quiet "0"

# get procfile env var
PROCFILE=$(dokku config:get $APP PROCFILE);

dokku_log_verbose_quiet "1"

dokku_log_verbose_quiet "PROCFILE=$PROCFILE"

dokku_log_verbose_quiet "2"

if [ -n "$PROCFILE" ]; then

dokku_log_info1 "Setting Procfile from config"

dokku_log_verbose_quiet "$PROCFILE"

CMD=$(cat << EOF
cd "/app" &&
echo "$PROCFILE" > Procfile
EOF
)

CID=$(docker run "${DOCKER_COMMIT_LABEL_ARGS[@]}" -d $IMAGE /bin/bash -c "$CMD")
test $(docker wait $CID) -eq 0

docker commit "${DOCKER_COMMIT_LABEL_ARGS[@]}" $CID $IMAGE > /dev/null

dokku_log_verbose_quiet "Procfile ready"

fi

